## Create a logistic regression to predict absenteeism

### Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

### Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2

## Create the targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(),
                   1,
                   0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4,1
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2,0
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4,1
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2,0

### A comment on the targets

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Daily Work Load Average', 'Distance to Work', 'Day of the Week'], axis = 1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,False,False,False,True,7,289,33,30,0,2,1,1
1,False,False,False,False,7,118,50,31,0,1,0,0
2,False,False,False,True,7,179,38,31,0,0,0,0
3,True,False,False,False,7,279,39,24,0,2,0,1
4,False,False,False,True,7,289,33,30,0,2,1,0

## Select the inputs for the regression

In [13]:
data_with_targets.shape

(700, 12)

In [14]:
data_with_targets.iloc[:,0:14]

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,False,False,False,True,7,289,33,30,0,2,1,1
1,False,False,False,False,7,118,50,31,0,1,0,0
2,False,False,False,True,7,179,38,31,0,0,0,0
3,True,False,False,False,7,279,39,24,0,2,0,1
4,False,False,False,True,7,289,33,30,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,179,40,22,1,2,0,1
696,True,False,False,False,5,225,28,24,0,1,2,0
697,True,False,False,False,5,330,28,25,1,0,0,1
698,False,False,False,True,5,235,32,25,1,0,0,0
699,False,False,False,True,5,291,40,25,0,1,1,0

In [15]:
data_with_targets.iloc[:,:-1]

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,False,False,False,True,7,289,33,30,0,2,1
1,False,False,False,False,7,118,50,31,0,1,0
2,False,False,False,True,7,179,38,31,0,0,0
3,True,False,False,False,7,279,39,24,0,2,0
4,False,False,False,True,7,289,33,30,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,179,40,22,1,2,0
696,True,False,False,False,5,225,28,24,0,1,2
697,True,False,False,False,5,330,28,25,1,0,0
698,False,False,False,True,5,235,32,25,1,0,0
699,False,False,False,True,5,291,40,25,0,1,1

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [17]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler()

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self,columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std) 
        self.columns = columns
        self.mean_ = None
        self.var_ = None

        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns]) 
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [19]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [20]:
# columns_to_scale = ['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work',
#        'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets']

columns_to_omit = ['Reason 1','Reason 2','Reason 3','Reason 4','Education']

In [21]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [22]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [23]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\kabir\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [24]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [25]:
scaled_inputs

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,False,False,False,True,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,False,False,False,False,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,False,False,False,True,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,True,False,False,False,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,False,False,False,True,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,True,False,False,False,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,True,False,False,False,-0.388293,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,False,False,False,True,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,False,False,False,True,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [26]:
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle

### Import the relevant module

In [27]:
from sklearn.model_selection import train_test_split

### Split

In [28]:
train_test_split(scaled_inputs, targets)

[     Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
 547     False     False     False      True     1.324766
 401     False     False      True     False    -0.959313
 299      True     False     False     False     1.039256
 263      True     False     False     False     0.468236
 492     False     False     False      True     0.468236
 ..        ...       ...       ...       ...          ...
 330      True     False     False     False     1.324766
 558      True     False     False     False     1.610276
 391     False     False      True     False    -0.959313
 187      True     False     False     False    -0.673803
 369     False     False     False      True    -1.244823

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 547                0.040034 -1.320435        -0.643782          0  -0.01928
 401                0.190942  0.091435         0.532229          1  -0.01928
 299               -0.654143 -1.006686        -1.819793          1  -0.91903
 263               -1.574681  2.130803         1.002633          0  -0.01928
 492               -1.574681  0.091435         0.297027          0  -0.91903
 ..                      ...       ...              ...        ...       ...
 330                0.356940  0.718933        -0.878984          0  -0.91903
 558               -0.654143 -1.006686        -1.819793          1  -0.91903
 391                0.356940  0.718933        -0.878984          0  -0.91903
 187                0.356940  0.718933        -0.878984          0  -0.91903
 369               -1.574681  0.091435         0.297027          0  -0.91903

          Pets
 547  1.126663
 401  0.268487
 299 -0.589690
 263 -0.589690
 492 -0.589690
 ..        ...
 330 -0.589690
 558 -0.589690
 391 -0.589690
 187 -0.589690
 369 -0.589690

 [525 rows x 11 columns],
      Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
 634      True     False     False     False    -0.959313
 397     False     False     False      True    -0.959313
 697      True     False     False     False    -0.388293
 524      True     False     False     False     1.039256
 321     False     False     False      True     1.324766
 ..        ...       ...       ...       ...          ...
 696      True     False     False     False    -0.388293
 132     False     False     False      True    -1.530333
 303     False     False     False     False     1.039256
 316     False     False     False      True     1.039256
 135     False     False     False      True    -1.530333

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 634               -0.654143  0.248310         1.002633          0 -0.919030
 397                2.348925 -0.065439        -1.349389          0  0.880469
 697                1.624567 -1.320435        -0.408580          1 -0.919030
 524                0.040034 -1.320435        -0.643782          0 -0.019280
 321                1.036026  0.562059        -0.408580          0 -0.019280
 ..                      ...       ...              ...        ...       ...
 696                0.040034 -1.320435        -0.643782          0 -0.019280
 132               -0.578689 -1.477309        -1.349389          0 -0.919030
 303                0.190942  1.032682         2.649049          0 -0.019280
 316               -1.574681  2.130803         1.002633          0 -0.019280
 135                0.040034 -1.320435        -0.643782          0 -0.019280

          Pets
 634 -0.589690
 397  2.843016
 697 -0.589690
 524  1.126663
 321  0.268487
 ..        ...
 696  1.126663
 132 -0.589690
 303 -0.589690
 316 -0.589690
 135  1.126663

 [175 rows x 11 columns],
 array([0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
        1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
        1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0]),
 array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0])]

In [29]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [30]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)

In [31]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)

## Logistic Regression with sklearn

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Train the model

In [33]:
reg = LogisticRegression()

In [34]:
reg.fit(x_train,y_train)

LogisticRegression()

In [35]:
reg.score(x_train,y_train)

0.7732142857142857

### Manually check the accuracy

In [36]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [37]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [38]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

In [39]:
np.sum(model_outputs==y_train)

433

In [40]:
model_outputs.shape[0]

560

In [41]:
np.sum(model_outputs==y_train) / model_outputs.shape[0]

0.7732142857142857

### Find the intercept and coefficients

In [42]:
reg.intercept_

array([-1.6474549])

In [43]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [44]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [45]:
feature_name = unscaled_inputs.columns.values

In [46]:
summary_table = pd.DataFrame(columns = ['Feature Name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

              Feature Name  Coefficient
0                 Reason 1     2.800197
1                 Reason 2     0.951884
2                 Reason 3     3.115553
3                 Reason 4     0.839001
4              Month Value     0.158930
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396

In [47]:
summary_table.index += 1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

              Feature Name  Coefficient
0                Intercept    -1.647455
1                 Reason 1     2.800197
2                 Reason 2     0.951884
3                 Reason 3     3.115553
4                 Reason 4     0.839001
5              Month Value     0.158930
6   Transportation Expense     0.605284
7                      Age    -0.169891
8          Body Mass Index     0.279811
9                Education    -0.210533
10                Children     0.348262
11                    Pets    -0.277396

### Interpreting the coefficients

In [48]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table

              Feature Name  Coefficient  Odds Ratio
0                Intercept    -1.647455    0.192539
1                 Reason 1     2.800197   16.447892
2                 Reason 2     0.951884    2.590585
3                 Reason 3     3.115553   22.545903
4                 Reason 4     0.839001    2.314054
5              Month Value     0.158930    1.172256
6   Transportation Expense     0.605284    1.831773
7                      Age    -0.169891    0.843757
8          Body Mass Index     0.279811    1.322880
9                Education    -0.210533    0.810152
10                Children     0.348262    1.416604
11                    Pets    -0.277396    0.757754

In [50]:
summary_table.sort_values('Odds Ratio', ascending = False)

              Feature Name  Coefficient  Odds Ratio
3                 Reason 3     3.115553   22.545903
1                 Reason 1     2.800197   16.447892
2                 Reason 2     0.951884    2.590585
4                 Reason 4     0.839001    2.314054
6   Transportation Expense     0.605284    1.831773
10                Children     0.348262    1.416604
8          Body Mass Index     0.279811    1.322880
5              Month Value     0.158930    1.172256
7                      Age    -0.169891    0.843757
9                Education    -0.210533    0.810152
11                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

## Testing the model

In [51]:
reg.score(x_test, y_test)

0.75

In [52]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.63043442, 0.36956558],
       [0.32093965, 0.67906035],
       [0.31497433, 0.68502567],
       [0.47131917, 0.52868083],
       [0.78159464, 0.21840536],
       [0.46493449, 0.53506551],
       [0.77852919, 0.22147081],
       [0.26307895, 0.73692105],
       [0.59501956, 0.40498044],
       [0.39494012, 0.60505988],
       [0.78924152, 0.21075848],
       [0.54775534, 0.45224466],
       [0.76248708, 0.23751292],
       [0.60166502, 0.39833498],
       [0.17244553, 0.82755447],
       [0.43202425, 0.56797575],
       [0.30886675, 0.69113325],
       [0.71340413, 0.28659587],
       [0.78064733, 0.21935267],
       [0.7966903 , 0.2033097 ],
       [0.42371744, 0.57628256],
       [0.6705336 , 0.3294664 ],
       [0.33487603, 0.66512397],
       [0.73050501, 0.26949499],
       [0.16678032, 0.83321968],
       [0.56508475, 0.43491525],
       [0.11625388, 0.88374612],
       [0.76872928, 0.23127072],
       [0.66584142, 0.33415858],
       [0.65567061, 0.34432939],
       [0.30090655, 0.69909345],
       [0.34505737, 0.65494263],
       [0.70755059, 0.29244941],
       [0.20799242, 0.79200758],
       [0.79249724, 0.20750276],
       [0.73159442, 0.26840558],
       [0.91291434, 0.08708566],
       [0.77852919, 0.22147081],
       [0.26754583, 0.73245417],
       [0.69469781, 0.30530219],
       [0.77852919, 0.22147081],
       [0.70985592, 0.29014408],
       [0.09561809, 0.90438191],
       [0.53938703, 0.46061297],
       [0.39825313, 0.60174687],
       [0.78159464, 0.21840536],
       [0.22645293, 0.77354707],
       [0.26837292, 0.73162708],
       [0.25831165, 0.74168835],
       [0.32855571, 0.67144429],
       [0.75417184, 0.24582816],
       [0.92387058, 0.07612942],
       [0.76872928, 0.23127072],
       [0.24741155, 0.75258845],
       [0.56558369, 0.43441631],
       [0.87775043, 0.12224957],
       [0.29572951, 0.70427049],
       [0.42037128, 0.57962872],
       [0.75881641, 0.24118359],
       [0.32093965, 0.67906035],
       [0.82488593, 0.17511407],
       [0.84950183, 0.15049817],
       [0.77374985, 0.22625015],
       [0.73159442, 0.26840558],
       [0.74903632, 0.25096368],
       [0.14944055, 0.85055945],
       [0.70403751, 0.29596249],
       [0.23713867, 0.76286133],
       [0.75645005, 0.24354995],
       [0.78203264, 0.21796736],
       [0.37671823, 0.62328177],
       [0.32093965, 0.67906035],
       [0.30409309, 0.69590691],
       [0.25542876, 0.74457124],
       [0.55063861, 0.44936139],
       [0.51677447, 0.48322553],
       [0.72259112, 0.27740888],
       [0.14944055, 0.85055945],
       [0.2220274 , 0.7779726 ],
       [0.85521156, 0.14478844],
       [0.93001302, 0.06998698],
       [0.09640551, 0.90359449],
       [0.33736668, 0.66263332],
       [0.66154998, 0.33845002],
       [0.47623876, 0.52376124],
       [0.43903262, 0.56096738],
       [0.21378105, 0.78621895],
       [0.17783793, 0.82216207],
       [0.45811539, 0.54188461],
       [0.6906917 , 0.3093083 ],
       [0.74041049, 0.25958951],
       [0.8393858 , 0.1606142 ],
       [0.18777875, 0.81222125],
       [0.54775534, 0.45224466],
       [0.78159464, 0.21840536],
       [0.64457904, 0.35542096],
       [0.78924152, 0.21075848],
       [0.89029009, 0.10970991],
       [0.25937462, 0.74062538],
       [0.7003009 , 0.2996991 ],
       [0.38415023, 0.61584977],
       [0.78924152, 0.21075848],
       [0.70403751, 0.29596249],
       [0.64457904, 0.35542096],
       [0.73490357, 0.26509643],
       [0.47623876, 0.52376124],
       [0.5392707 , 0.4607293 ],
       [0.68498978, 0.31501022],
       [0.75645005, 0.24354995],
       [0.53938703, 0.46061297]])

In [53]:
predicted_proba.shape

(140, 2)

In [54]:
predicted_proba[:,1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174687,
       0.21840536, 0.77354707, 0.73162708, 0.74168835, 0.67144429,
       0.24582816, 0.07612942, 0.23127072, 0.75258845, 0.43441631,
       0.12224957, 0.70427049, 0.57962872, 0.24118359, 0.67906035,
       0.17511407, 0.15049817, 0.22625015, 0.26840558, 0.25096368,
       0.85055945, 0.29596249, 0.76286133, 0.24354995, 0.21796736,
       0.62328177, 0.67906035, 0.69590691, 0.74457124, 0.44936139,
       0.48322553, 0.27740888, 0.85055945, 0.7779726 , 0.14478844,
       0.06998698, 0.90359449, 0.66263332, 0.33845002, 0.52376124,
       0.56096738, 0.78621895, 0.82216207, 0.54188461, 0.3093083 ,
       0.25958951, 0.1606142 , 0.81222125, 0.45224466, 0.21840536,
       0.35542096, 0.21075848, 0.10970991, 0.74062538, 0.2996991 ,
       0.61584977, 0.21075848, 0.29596249, 0.35542096, 0.26509643,
       0.52376124, 0.4607293 , 0.31501022, 0.24354995, 0.46061297])

## Save the model

In [55]:
import pickle

In [56]:
with open('model','wb') as file:
    pickle.dump(reg, file)

In [57]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)